name: Erlang CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize", "reopened"]

permissions:
  contents: read

jobs:
  #============================================================================
  # Build
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.0
          rebar3-version: 3.22.1
      - run: rebar3 compile

  #============================================================================
  # Static Analysis
  static_analysis:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.0
          rebar3-version: 3.22.1
      - run: rebar3 xref
      - run: rebar3 dialyzer

  #============================================================================
  # Test
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.0
          rebar3-version: 3.22.1
      - name: Run sample-based-tests
        run: rebar3 do eunit, ct
      - name: Run property-based-tests
        run: rebar3 proper -n 500
