name: Erlang CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["opened", "synchronize", "reopened"]

permissions:
  contents: read

jobs:
  build:
    # NOTE: Run on Ubuntu of Docker in my computer
    runs-on: ubuntu-22.04

    container:
      image: erlang:26.2.1

    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: rebar3 compile
      - name: Check statically
        run: rebar3 check
      - name: Run sample-based-tests
        run: rebar3 do eunit, ct
      - name: Run property-based-tests
        run: rebar3 proper -n 500
