name: Run property-based tests periodically

on:
  schedule:
    # NOTE: Every day at 00:00 (JST)
    - cron: "0 15 * * *"

env:
  otp: 26.0
  rebar3: 3.22.1

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp }}
          rebar3-version: ${{ env.rebar3 }}
      - name: Run property-based tests
        run: rebar3 proper -n 1000
